version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATABASE=WakfuBuilder_db

  app:
    build:
      context: ./springBoot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb


  front:
    build:
      context: ./front
    ports:
      - "4200:4200"
    depends_on:
      - app
      - mongodb

volumes:
  mongodb_data: